import 'package:colosynth/game/logic/direction.dart';

class SynthDefinition {
  final String id;
  final String name;
  final List<AttackDirection> comboSequence;
  final int counterStaminaDamage;
  final double bonusDamageMult;
  final int activeSkillChargeBonus;
  final int unlockCostPaint;
  final int unlockCostInk;

  const SynthDefinition({
    required this.id,
    required this.name,
    required this.comboSequence,
    required this.counterStaminaDamage,
    required this.bonusDamageMult,
    required this.activeSkillChargeBonus,
    required this.unlockCostPaint,
    required this.unlockCostInk,
  });

  /// Returns the combo sequence hardcoded/capped to a max length of 5 directions.
  List<AttackDirection> get effectiveSequence =>
      comboSequence.length > 5 ? comboSequence.sublist(0, 5) : comboSequence;

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'comboSequence': effectiveSequence.map((e) => e.index).toList(),
        'counterStaminaDamage': counterStaminaDamage,
        'bonusDamageMult': bonusDamageMult,
        'activeSkillChargeBonus': activeSkillChargeBonus,
        'unlockCostPaint': unlockCostPaint,
        'unlockCostInk': unlockCostInk,
      };

  factory SynthDefinition.fromJson(Map<String, dynamic> json) {
    return SynthDefinition(
      id: json['id'] as String,
      name: json['name'] as String,
      comboSequence: (json['comboSequence'] as List<dynamic>)
          .map((e) => AttackDirection.values[e as int])
          .take(5)
          .toList(),
      counterStaminaDamage: (json['counterStaminaDamage'] ?? json['staggerStaminaDamage']) as int,
      bonusDamageMult: (json['bonusDamageMult'] as num).toDouble(),
      activeSkillChargeBonus: json['activeSkillChargeBonus'] as int,
      unlockCostPaint: json['unlockCostPaint'] as int,
      unlockCostInk: json['unlockCostInk'] as int,
    );
  }
}

const List<SynthDefinition> globalSynthDefinitions = [
  SynthDefinition(
    id: 'synth_01',
    name: 'Standard Strike',
    comboSequence: [AttackDirection.n, AttackDirection.s],
    counterStaminaDamage: 10,
    bonusDamageMult: 1.2,
    activeSkillChargeBonus: 5,
    unlockCostPaint: 10,
    unlockCostInk: 50,
  ),
  SynthDefinition(
    id: 'synth_02',
    name: 'Rapid Cross',
    comboSequence: [AttackDirection.e, AttackDirection.w, AttackDirection.e],
    counterStaminaDamage: 15,
    bonusDamageMult: 1.5,
    activeSkillChargeBonus: 8,
    unlockCostPaint: 15,
    unlockCostInk: 80,
  ),
  SynthDefinition(
    id: 'synth_03',
    name: 'Rising Wind',
    comboSequence: [AttackDirection.s, AttackDirection.n, AttackDirection.n],
    counterStaminaDamage: 20,
    bonusDamageMult: 1.4,
    activeSkillChargeBonus: 10,
    unlockCostPaint: 20,
    unlockCostInk: 100,
  ),
  SynthDefinition(
    id: 'synth_04',
    name: 'Ground Slam',
    comboSequence: [AttackDirection.n, AttackDirection.n, AttackDirection.s],
    counterStaminaDamage: 25,
    bonusDamageMult: 1.6,
    activeSkillChargeBonus: 12,
    unlockCostPaint: 25,
    unlockCostInk: 120,
  ),
  SynthDefinition(
    id: 'synth_05',
    name: 'Vortex Spin',
    comboSequence: [AttackDirection.ne, AttackDirection.sw, AttackDirection.ne],
    counterStaminaDamage: 18,
    bonusDamageMult: 1.35,
    activeSkillChargeBonus: 10,
    unlockCostPaint: 30,
    unlockCostInk: 150,
  ),
  SynthDefinition(
    id: 'synth_06',
    name: 'Shadow Pierce',
    comboSequence: [AttackDirection.w, AttackDirection.e, AttackDirection.w],
    counterStaminaDamage: 12,
    bonusDamageMult: 1.45,
    activeSkillChargeBonus: 8,
    unlockCostPaint: 35,
    unlockCostInk: 175,
  ),
  SynthDefinition(
    id: 'synth_07',
    name: 'Solar Flare',
    comboSequence: [AttackDirection.n, AttackDirection.e, AttackDirection.s],
    counterStaminaDamage: 22,
    bonusDamageMult: 1.5,
    activeSkillChargeBonus: 15,
    unlockCostPaint: 40,
    unlockCostInk: 200,
  ),
  SynthDefinition(
    id: 'synth_08',
    name: 'Lunar Eclipse',
    comboSequence: [AttackDirection.s, AttackDirection.w, AttackDirection.n],
    counterStaminaDamage: 24,
    bonusDamageMult: 1.4,
    activeSkillChargeBonus: 14,
    unlockCostPaint: 45,
    unlockCostInk: 220,
  ),
  SynthDefinition(
    id: 'synth_09',
    name: 'Thunder Clap',
    comboSequence: [AttackDirection.nw, AttackDirection.se],
    counterStaminaDamage: 30,
    bonusDamageMult: 1.7,
    activeSkillChargeBonus: 10,
    unlockCostPaint: 50,
    unlockCostInk: 250,
  ),
  SynthDefinition(
    id: 'synth_10',
    name: 'Frost Bite',
    comboSequence: [AttackDirection.sw, AttackDirection.ne],
    counterStaminaDamage: 28,
    bonusDamageMult: 1.65,
    activeSkillChargeBonus: 9,
    unlockCostPaint: 55,
    unlockCostInk: 280,
  ),
  SynthDefinition(
    id: 'synth_11',
    name: 'Gale Slash',
    comboSequence: [AttackDirection.n, AttackDirection.ne, AttackDirection.e],
    counterStaminaDamage: 15,
    bonusDamageMult: 1.3,
    activeSkillChargeBonus: 10,
    unlockCostPaint: 60,
    unlockCostInk: 300,
  ),
  SynthDefinition(
    id: 'synth_12',
    name: 'Earthquake',
    comboSequence: [AttackDirection.s, AttackDirection.sw, AttackDirection.w],
    counterStaminaDamage: 35,
    bonusDamageMult: 1.8,
    activeSkillChargeBonus: 5,
    unlockCostPaint: 65,
    unlockCostInk: 320,
  ),
  SynthDefinition(
    id: 'synth_13',
    name: 'Magma Surge',
    comboSequence: [AttackDirection.n, AttackDirection.nw, AttackDirection.w],
    counterStaminaDamage: 32,
    bonusDamageMult: 1.75,
    activeSkillChargeBonus: 6,
    unlockCostPaint: 70,
    unlockCostInk: 350,
  ),
  SynthDefinition(
    id: 'synth_14',
    name: 'Tidal Wave',
    comboSequence: [AttackDirection.s, AttackDirection.se, AttackDirection.e],
    counterStaminaDamage: 20,
    bonusDamageMult: 1.4,
    activeSkillChargeBonus: 12,
    unlockCostPaint: 75,
    unlockCostInk: 380,
  ),
  SynthDefinition(
    id: 'synth_15',
    name: 'Storm Strike',
    comboSequence: [AttackDirection.ne, AttackDirection.e, AttackDirection.se],
    counterStaminaDamage: 25,
    bonusDamageMult: 1.55,
    activeSkillChargeBonus: 10,
    unlockCostPaint: 80,
    unlockCostInk: 400,
  ),
  SynthDefinition(
    id: 'synth_16',
    name: 'Cyclone Spin',
    comboSequence: [AttackDirection.nw, AttackDirection.w, AttackDirection.sw],
    counterStaminaDamage: 21,
    bonusDamageMult: 1.42,
    activeSkillChargeBonus: 11,
    unlockCostPaint: 85,
    unlockCostInk: 420,
  ),
  SynthDefinition(
    id: 'synth_17',
    name: 'Blaze Burst',
    comboSequence: [AttackDirection.e, AttackDirection.se, AttackDirection.s],
    counterStaminaDamage: 27,
    bonusDamageMult: 1.6,
    activeSkillChargeBonus: 8,
    unlockCostPaint: 90,
    unlockCostInk: 450,
  ),
  SynthDefinition(
    id: 'synth_18',
    name: 'Abyssal Grip',
    comboSequence: [AttackDirection.w, AttackDirection.nw, AttackDirection.n],
    counterStaminaDamage: 29,
    bonusDamageMult: 1.5,
    activeSkillChargeBonus: 12,
    unlockCostPaint: 95,
    unlockCostInk: 480,
  ),
  SynthDefinition(
    id: 'synth_19',
    name: 'Heavenly Sword',
    comboSequence: [AttackDirection.n, AttackDirection.s, AttackDirection.n],
    counterStaminaDamage: 33,
    bonusDamageMult: 1.8,
    activeSkillChargeBonus: 15,
    unlockCostPaint: 100,
    unlockCostInk: 500,
  ),
  SynthDefinition(
    id: 'synth_20',
    name: 'Void Pierce',
    comboSequence: [AttackDirection.s, AttackDirection.n, AttackDirection.s],
    counterStaminaDamage: 31,
    bonusDamageMult: 1.78,
    activeSkillChargeBonus: 14,
    unlockCostPaint: 110,
    unlockCostInk: 550,
  ),
  SynthDefinition(
    id: 'synth_21',
    name: 'Dragon Claw',
    comboSequence: [AttackDirection.e, AttackDirection.w, AttackDirection.s],
    counterStaminaDamage: 26,
    bonusDamageMult: 1.62,
    activeSkillChargeBonus: 10,
    unlockCostPaint: 120,
    unlockCostInk: 600,
  ),
  SynthDefinition(
    id: 'synth_22',
    name: 'Phoenix Wing',
    comboSequence: [AttackDirection.w, AttackDirection.e, AttackDirection.n],
    counterStaminaDamage: 24,
    bonusDamageMult: 1.58,
    activeSkillChargeBonus: 13,
    unlockCostPaint: 130,
    unlockCostInk: 650,
  ),
  SynthDefinition(
    id: 'synth_23',
    name: 'Tiger Pounce',
    comboSequence: [AttackDirection.n, AttackDirection.w, AttackDirection.e],
    counterStaminaDamage: 28,
    bonusDamageMult: 1.7,
    activeSkillChargeBonus: 11,
    unlockCostPaint: 140,
    unlockCostInk: 700,
  ),
  SynthDefinition(
    id: 'synth_24',
    name: 'Serpent Coil',
    comboSequence: [AttackDirection.s, AttackDirection.e, AttackDirection.w],
    counterStaminaDamage: 22,
    bonusDamageMult: 1.48,
    activeSkillChargeBonus: 16,
    unlockCostPaint: 150,
    unlockCostInk: 750,
  ),
  SynthDefinition(
    id: 'synth_25',
    name: 'Meteor Strike',
    comboSequence: [AttackDirection.ne, AttackDirection.se, AttackDirection.n],
    counterStaminaDamage: 40,
    bonusDamageMult: 2.0,
    activeSkillChargeBonus: 8,
    unlockCostPaint: 160,
    unlockCostInk: 800,
  ),
  SynthDefinition(
    id: 'synth_26',
    name: 'Comet Dust',
    comboSequence: [AttackDirection.nw, AttackDirection.sw, AttackDirection.s],
    counterStaminaDamage: 38,
    bonusDamageMult: 1.95,
    activeSkillChargeBonus: 9,
    unlockCostPaint: 170,
    unlockCostInk: 850,
  ),
  SynthDefinition(
    id: 'synth_27',
    name: 'Gravity Well',
    comboSequence: [AttackDirection.se, AttackDirection.nw, AttackDirection.e],
    counterStaminaDamage: 36,
    bonusDamageMult: 1.85,
    activeSkillChargeBonus: 11,
    unlockCostPaint: 180,
    unlockCostInk: 900,
  ),
  SynthDefinition(
    id: 'synth_28',
    name: 'Nebula Slash',
    comboSequence: [AttackDirection.sw, AttackDirection.ne, AttackDirection.w],
    counterStaminaDamage: 34,
    bonusDamageMult: 1.8,
    activeSkillChargeBonus: 12,
    unlockCostPaint: 190,
    unlockCostInk: 950,
  ),
  SynthDefinition(
    id: 'synth_29',
    name: 'Cosmic Ray',
    comboSequence: [AttackDirection.n, AttackDirection.e, AttackDirection.w],
    counterStaminaDamage: 30,
    bonusDamageMult: 1.72,
    activeSkillChargeBonus: 14,
    unlockCostPaint: 200,
    unlockCostInk: 1000,
  ),
  SynthDefinition(
    id: 'synth_30',
    name: 'Supernova',
    comboSequence: [AttackDirection.s, AttackDirection.w, AttackDirection.e],
    counterStaminaDamage: 45,
    bonusDamageMult: 2.2,
    activeSkillChargeBonus: 20,
    unlockCostPaint: 220,
    unlockCostInk: 1100,
  ),
  SynthDefinition(
    id: 'synth_31',
    name: 'Spitfire',
    comboSequence: [AttackDirection.e, AttackDirection.n],
    counterStaminaDamage: 12,
    bonusDamageMult: 1.25,
    activeSkillChargeBonus: 6,
    unlockCostPaint: 25,
    unlockCostInk: 100,
  ),
  SynthDefinition(
    id: 'synth_32',
    name: 'Quickdraw',
    comboSequence: [AttackDirection.w, AttackDirection.s],
    counterStaminaDamage: 14,
    bonusDamageMult: 1.3,
    activeSkillChargeBonus: 7,
    unlockCostPaint: 30,
    unlockCostInk: 120,
  ),
  SynthDefinition(
    id: 'synth_33',
    name: 'Starlight Blast',
    comboSequence: [AttackDirection.n, AttackDirection.ne, AttackDirection.nw],
    counterStaminaDamage: 22,
    bonusDamageMult: 1.5,
    activeSkillChargeBonus: 13,
    unlockCostPaint: 85,
    unlockCostInk: 430,
  ),
  SynthDefinition(
    id: 'synth_34',
    name: 'Quake Wave',
    comboSequence: [AttackDirection.s, AttackDirection.se, AttackDirection.sw],
    counterStaminaDamage: 26,
    bonusDamageMult: 1.6,
    activeSkillChargeBonus: 9,
    unlockCostPaint: 95,
    unlockCostInk: 470,
  ),
  SynthDefinition(
    id: 'synth_35',
    name: 'Lightning Bolt',
    comboSequence: [AttackDirection.e, AttackDirection.ne, AttackDirection.se],
    counterStaminaDamage: 20,
    bonusDamageMult: 1.52,
    activeSkillChargeBonus: 15,
    unlockCostPaint: 105,
    unlockCostInk: 520,
  ),
  SynthDefinition(
    id: 'synth_36',
    name: 'Venom Bite',
    comboSequence: [AttackDirection.w, AttackDirection.nw, AttackDirection.sw],
    counterStaminaDamage: 18,
    bonusDamageMult: 1.48,
    activeSkillChargeBonus: 14,
    unlockCostPaint: 115,
    unlockCostInk: 570,
  ),
  SynthDefinition(
    id: 'synth_37',
    name: 'Iron Wall',
    comboSequence: [AttackDirection.n, AttackDirection.s, AttackDirection.s],
    counterStaminaDamage: 28,
    bonusDamageMult: 1.3,
    activeSkillChargeBonus: 8,
    unlockCostPaint: 125,
    unlockCostInk: 620,
  ),
  SynthDefinition(
    id: 'synth_38',
    name: 'Raging Bull',
    comboSequence: [AttackDirection.s, AttackDirection.s, AttackDirection.n],
    counterStaminaDamage: 32,
    bonusDamageMult: 1.7,
    activeSkillChargeBonus: 7,
    unlockCostPaint: 135,
    unlockCostInk: 670,
  ),
  SynthDefinition(
    id: 'synth_39',
    name: 'Mirror Image',
    comboSequence: [AttackDirection.e, AttackDirection.w, AttackDirection.n],
    counterStaminaDamage: 15,
    bonusDamageMult: 1.4,
    activeSkillChargeBonus: 18,
    unlockCostPaint: 145,
    unlockCostInk: 720,
  ),
  SynthDefinition(
    id: 'synth_40',
    name: 'Shadowstep',
    comboSequence: [AttackDirection.w, AttackDirection.e, AttackDirection.s],
    counterStaminaDamage: 17,
    bonusDamageMult: 1.42,
    activeSkillChargeBonus: 17,
    unlockCostPaint: 155,
    unlockCostInk: 770,
  ),
  SynthDefinition(
    id: 'synth_41',
    name: 'Arcane Surge',
    comboSequence: [AttackDirection.ne, AttackDirection.se, AttackDirection.sw],
    counterStaminaDamage: 27,
    bonusDamageMult: 1.68,
    activeSkillChargeBonus: 12,
    unlockCostPaint: 165,
    unlockCostInk: 820,
  ),
  SynthDefinition(
    id: 'synth_42',
    name: 'Soul Reap',
    comboSequence: [AttackDirection.nw, AttackDirection.sw, AttackDirection.se],
    counterStaminaDamage: 29,
    bonusDamageMult: 1.72,
    activeSkillChargeBonus: 11,
    unlockCostPaint: 175,
    unlockCostInk: 870,
  ),
  SynthDefinition(
    id: 'synth_43',
    name: 'Solar Shield',
    comboSequence: [AttackDirection.n, AttackDirection.e, AttackDirection.e],
    counterStaminaDamage: 22,
    bonusDamageMult: 1.35,
    activeSkillChargeBonus: 13,
    unlockCostPaint: 185,
    unlockCostInk: 920,
  ),
  SynthDefinition(
    id: 'synth_44',
    name: 'Lunar Veil',
    comboSequence: [AttackDirection.s, AttackDirection.w, AttackDirection.w],
    counterStaminaDamage: 24,
    bonusDamageMult: 1.38,
    activeSkillChargeBonus: 12,
    unlockCostPaint: 195,
    unlockCostInk: 970,
  ),
  SynthDefinition(
    id: 'synth_45',
    name: 'Infinity Edge',
    comboSequence: [AttackDirection.n, AttackDirection.s, AttackDirection.e],
    counterStaminaDamage: 38,
    bonusDamageMult: 1.9,
    activeSkillChargeBonus: 10,
    unlockCostPaint: 210,
    unlockCostInk: 1050,
  ),
  SynthDefinition(
    id: 'synth_46',
    name: 'Cataclysm',
    comboSequence: [AttackDirection.s, AttackDirection.n, AttackDirection.w],
    counterStaminaDamage: 42,
    bonusDamageMult: 2.1,
    activeSkillChargeBonus: 15,
    unlockCostPaint: 230,
    unlockCostInk: 1150,
  ),
  SynthDefinition(
    id: 'synth_47',
    name: 'Judgment Day',
    comboSequence: [AttackDirection.e, AttackDirection.e, AttackDirection.w],
    counterStaminaDamage: 48,
    bonusDamageMult: 2.3,
    activeSkillChargeBonus: 25,
    unlockCostPaint: 250,
    unlockCostInk: 1250,
  ),
  SynthDefinition(
    id: 'synth_48',
    name: 'Divine Wrath',
    comboSequence: [AttackDirection.w, AttackDirection.w, AttackDirection.e],
    counterStaminaDamage: 46,
    bonusDamageMult: 2.25,
    activeSkillChargeBonus: 24,
    unlockCostPaint: 240,
    unlockCostInk: 1200,
  ),
  SynthDefinition(
    id: 'synth_49',
    name: 'Starfall',
    comboSequence: [AttackDirection.n, AttackDirection.n, AttackDirection.n],
    counterStaminaDamage: 50,
    bonusDamageMult: 2.4,
    activeSkillChargeBonus: 30,
    unlockCostPaint: 300,
    unlockCostInk: 1500,
  ),
  SynthDefinition(
    id: 'synth_50',
    name: 'End of Days',
    comboSequence: [AttackDirection.s, AttackDirection.s, AttackDirection.s],
    counterStaminaDamage: 50,
    bonusDamageMult: 2.5,
    activeSkillChargeBonus: 30,
    unlockCostPaint: 300,
    unlockCostInk: 1500,
  ),
];
