import 'package:flutter/material.dart';
import 'package:colosynth/game_data/character_type.dart';

abstract final class CharacterDatabase {
  static const List<CharacterData> all = [
    CharacterData(
      id: 'arthur',
      name: 'Arthur',
      role: 'Warrior',
      accentColor: Color(0xFFFFD600),
      description: 'A powerful knight!',
      paintCost: 0,
      rarity: CharacterRarity.common,
      icon: Icons.shield,
      stats: [
        CharacterStat(label: 'HP', value: 90),
        CharacterStat(label: 'ATK', value: 65),
        CharacterStat(label: 'DEF', value: 85),
        CharacterStat(label: 'SPD', value: 45),
        CharacterStat(label: 'MGC', value: 50),
      ],
      activeSkill: CharacterSkill(
        name: 'arthur_active',
        description: 'Strikes out a powerful slash and stuns enemy',
        icon: Icons.bolt,
      ),
      passiveSkill: CharacterSkill(
        name: 'arthur_passive',
        description: 'restore 20%HP when active skills is used',
        icon: Icons.favorite,
      ),
    ),
    CharacterData(
      id: 'lilith',
      name: 'Lilith',
      role: 'mage',
      accentColor: Color(0xFF8B5CF6),
      description: 'A strong and cute spell caster!',
      paintCost: 480,
      rarity: CharacterRarity.legendary,
      hoursLeft: 47,
      icon: Icons.flash_on,
      stats: [
        CharacterStat(label: 'HP', value: 55),
        CharacterStat(label: 'ATK', value: 95),
        CharacterStat(label: 'DEF', value: 35),
        CharacterStat(label: 'SPD', value: 92),
        CharacterStat(label: 'MGC', value: 70),
      ],
      activeSkill: CharacterSkill(
        name: 'lilith_active',
        description: 'summon a nuke blast',
        icon: Icons.flash_on,
      ),
      passiveSkill: CharacterSkill(
        name: 'lilith_passive',
        description: 'generate a shield every 10 seconds',
        icon: Icons.dark_mode,
      ),
    ),
    CharacterData(
      id: 'centrium',
      name: 'Centrium',
      role: 'blader',
      accentColor: Color(0xFF00BCD4),
      description: 'A strong and cool blader!',
      paintCost: 350,
      rarity: CharacterRarity.rare,
      icon: Icons.thunderstorm,
      stats: [
        CharacterStat(label: 'HP', value: 70),
        CharacterStat(label: 'ATK', value: 80),
        CharacterStat(label: 'DEF', value: 60),
        CharacterStat(label: 'SPD', value: 38),
        CharacterStat(label: 'MGC', value: 98),
      ],
      activeSkill: CharacterSkill(
        name: 'centrium_active',
        description: 'Releases a lightning burst',
        icon: Icons.thunderstorm,
      ),
      passiveSkill: CharacterSkill(
        name: 'centrium_passive',
        description: 'terminate enemy below 8% HP',
        icon: Icons.terrain,
      ),
    ),
    CharacterData(
      id: 'char_04',
      name: 'Centurio',
      role: 'Guardian',
      accentColor: Color(0xFFE91E63),
      description: 'A steadfast defensive guardian.',
      paintCost: 500,
      rarity: CharacterRarity.rare,
      icon: Icons.security,
      stats: [
        CharacterStat(label: 'HP', value: 95),
        CharacterStat(label: 'ATK', value: 50),
        CharacterStat(label: 'DEF', value: 90),
        CharacterStat(label: 'SPD', value: 30),
        CharacterStat(label: 'MGC', value: 40),
      ],
      activeSkill: CharacterSkill(
        name: 'char_04_active',
        description: 'Greatly increases DEF for 8 seconds.',
        icon: Icons.security,
      ),
      passiveSkill: CharacterSkill(
        name: 'char_04_passive',
        description: 'Reflects 10% of damage taken.',
        icon: Icons.warning,
      ),
    ),
    CharacterData(
      id: 'char_05',
      name: 'Valeria',
      role: 'Valkyrie',
      accentColor: Color(0xFF9C27B0),
      description: 'A fierce warrior from the heavens.',
      paintCost: 500,
      rarity: CharacterRarity.rare,
      icon: Icons.gavel,
      stats: [
        CharacterStat(label: 'HP', value: 80),
        CharacterStat(label: 'ATK', value: 85),
        CharacterStat(label: 'DEF', value: 65),
        CharacterStat(label: 'SPD', value: 60),
        CharacterStat(label: 'MGC', value: 50),
      ],
      activeSkill: CharacterSkill(
        name: 'char_05_active',
        description: 'Deals heavy damage to the target.',
        icon: Icons.gavel,
      ),
      passiveSkill: CharacterSkill(
        name: 'char_05_passive',
        description: 'Gain 2% ATK for each successful hit.',
        icon: Icons.offline_bolt,
      ),
    ),
    CharacterData(
      id: 'char_06',
      name: 'Kaelen',
      role: 'Rogue',
      accentColor: Color(0xFF4CAF50),
      description: 'A swift thief operating in shadows.',
      paintCost: 500,
      rarity: CharacterRarity.rare,
      icon: Icons.gesture,
      stats: [
        CharacterStat(label: 'HP', value: 60),
        CharacterStat(label: 'ATK', value: 75),
        CharacterStat(label: 'DEF', value: 45),
        CharacterStat(label: 'SPD', value: 95),
        CharacterStat(label: 'MGC', value: 30),
      ],
      activeSkill: CharacterSkill(
        name: 'char_06_active',
        description: 'Instantly teleports behind the target.',
        icon: Icons.directions_run,
      ),
      passiveSkill: CharacterSkill(
        name: 'char_06_passive',
        description: 'Crits deal 20% additional damage.',
        icon: Icons.center_focus_strong,
      ),
    ),
    CharacterData(
      id: 'char_07',
      name: 'Sariel',
      role: 'Angel',
      accentColor: Color(0xFFFF9800),
      description: 'A messenger of holy light.',
      paintCost: 500,
      rarity: CharacterRarity.rare,
      icon: Icons.wb_sunny,
      stats: [
        CharacterStat(label: 'HP', value: 65),
        CharacterStat(label: 'ATK', value: 70),
        CharacterStat(label: 'DEF', value: 55),
        CharacterStat(label: 'SPD', value: 70),
        CharacterStat(label: 'MGC', value: 85),
      ],
      activeSkill: CharacterSkill(
        name: 'char_07_active',
        description: 'Heals the user and stuns nearby targets.',
        icon: Icons.wb_sunny,
      ),
      passiveSkill: CharacterSkill(
        name: 'char_07_passive',
        description: 'Reduces skill cooldowns by 10%.',
        icon: Icons.timer,
      ),
    ),
    CharacterData(
      id: 'char_08',
      name: 'Vargas',
      role: 'Berserker',
      accentColor: Color(0xFF795548),
      description: 'A warrior fueled by pure rage.',
      paintCost: 500,
      rarity: CharacterRarity.rare,
      icon: Icons.whatshot,
      stats: [
        CharacterStat(label: 'HP', value: 100),
        CharacterStat(label: 'ATK', value: 90),
        CharacterStat(label: 'DEF', value: 30),
        CharacterStat(label: 'SPD', value: 50),
        CharacterStat(label: 'MGC', value: 20),
      ],
      activeSkill: CharacterSkill(
        name: 'char_08_active',
        description: 'Increases ATK by 50% but lowers DEF.',
        icon: Icons.whatshot,
      ),
      passiveSkill: CharacterSkill(
        name: 'char_08_passive',
        description: 'Deals more damage as HP drops.',
        icon: Icons.trending_down,
      ),
    ),
    CharacterData(
      id: 'char_09',
      name: 'Lyra',
      role: 'Archer',
      accentColor: Color(0xFF607D8B),
      description: 'A quiet ranger of the deep woods.',
      paintCost: 500,
      rarity: CharacterRarity.rare,
      icon: Icons.gps_fixed,
      stats: [
        CharacterStat(label: 'HP', value: 55),
        CharacterStat(label: 'ATK', value: 80),
        CharacterStat(label: 'DEF', value: 40),
        CharacterStat(label: 'SPD', value: 85),
        CharacterStat(label: 'MGC', value: 45),
      ],
      activeSkill: CharacterSkill(
        name: 'char_09_active',
        description: 'Shoots multiple arrows at once.',
        icon: Icons.grain,
      ),
      passiveSkill: CharacterSkill(
        name: 'char_09_passive',
        description: 'Increases dodge rate by 15%.',
        icon: Icons.remove_red_eye,
      ),
    ),
    CharacterData(
      id: 'char_10',
      name: 'Ignis',
      role: 'Pyromancer',
      accentColor: Color(0xFFFF5722),
      description: 'A master of flame and fire magic.',
      paintCost: 500,
      rarity: CharacterRarity.rare,
      icon: Icons.local_fire_department,
      stats: [
        CharacterStat(label: 'HP', value: 60),
        CharacterStat(label: 'ATK', value: 90),
        CharacterStat(label: 'DEF', value: 35),
        CharacterStat(label: 'SPD', value: 65),
        CharacterStat(label: 'MGC', value: 90),
      ],
      activeSkill: CharacterSkill(
        name: 'char_10_active',
        description: 'Launches a high-explosive fireball.',
        icon: Icons.local_fire_department,
      ),
      passiveSkill: CharacterSkill(
        name: 'char_10_passive',
        description: 'Attacks burn the target for periodic damage.',
        icon: Icons.fireplace,
      ),
    ),
    CharacterData(
      id: 'char_11',
      name: 'Zephyr',
      role: 'Windrunner',
      accentColor: Color(0xFF8BC34A),
      description: 'A scout carrying the speed of the winds.',
      paintCost: 500,
      rarity: CharacterRarity.rare,
      icon: Icons.air,
      stats: [
        CharacterStat(label: 'HP', value: 70),
        CharacterStat(label: 'ATK', value: 70),
        CharacterStat(label: 'DEF', value: 55),
        CharacterStat(label: 'SPD', value: 90),
        CharacterStat(label: 'MGC', value: 50),
      ],
      activeSkill: CharacterSkill(
        name: 'char_11_active',
        description: 'Cyclone Strike',
        icon: Icons.air,
      ),
      passiveSkill: CharacterSkill(
        name: 'char_11_passive',
        description: 'Increases movement speed by 15%.',
        icon: Icons.speed,
      ),
    ),
    CharacterData(
      id: 'char_12',
      name: 'Sylvia',
      role: 'Assassin',
      accentColor: Color(0xFF3F51B5),
      description: 'An elite assassin from the shadows.',
      paintCost: 500,
      rarity: CharacterRarity.rare,
      icon: Icons.colorize,
      stats: [
        CharacterStat(label: 'HP', value: 50),
        CharacterStat(label: 'ATK', value: 99),
        CharacterStat(label: 'DEF', value: 30),
        CharacterStat(label: 'SPD', value: 95),
        CharacterStat(label: 'MGC', value: 40),
      ],
      activeSkill: CharacterSkill(
        name: 'char_12_active',
        description: 'Hits critical vulnerabilities with extreme damage.',
        icon: Icons.colorize,
      ),
      passiveSkill: CharacterSkill(
        name: 'char_12_passive',
        description: 'Gain 25% ATK bonus on targets under 30% HP.',
        icon: Icons.remove_circle,
      ),
    ),
  ];

  static CharacterData? findById(String id) {
    try {
      return all.firstWhere((c) => c.id == id);
    } catch (_) {
      return null;
    }
  }
}
